# Generated by Django 2.2 on 2019-04-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Credits', models.PositiveSmallIntegerField()),
                ('State', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('Dni', models.CharField(max_length=8)),
                ('birthDate', models.DateField()),
                ('Gnre', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentDate', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicManagement.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicManagement.Student')),
            ],
        ),
    ]
